# Generated by Django 4.1.9 on 2023-06-02 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_string', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorequest',
            name='request_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='videorequest',
            name='text',
            field=models.CharField(default='some text', max_length=100),
            preserve_default=False,
        ),
    ]
